

def var1():
    (T1M_GFX, T1M_MAIN, T1M_RES, T1M_CPU, T1M_MemAvailable, T1M_Memfree, T1M_PSS, T1M_USS,
    T2M_GFX, T2M_MAIN, T2M_RES, T2M_CPU, T2M_MemAvailable, T2M_Memfree, T2M_PSS, T2M_USS,
    T3M_GFX, T3M_MAIN, T3M_RES, T3M_CPU, T3M_MemAvailable, T3M_Memfree, T3M_PSS, T3M_USS,
    T4M_GFX, T4M_MAIN, T4M_RES, T4M_CPU, T4M_MemAvailable, T4M_Memfree, T4M_PSS, T4M_USS,
    T5M_GFX, T5M_MAIN, T5M_RES, T5M_CPU, T5M_MemAvailable, T5M_Memfree, T5M_PSS, T5M_USS,
    T6M_GFX, T6M_MAIN, T6M_RES, T6M_CPU, T6M_MemAvailable, T6M_Memfree, T6M_PSS, T6M_USS,
    T7M_GFX, T7M_MAIN, T7M_RES, T7M_CPU, T7M_MemAvailable, T7M_Memfree, T7M_PSS, T7M_USS,
    T8M_GFX, T8M_MAIN, T8M_RES, T8M_CPU, T8M_MemAvailable, T8M_Memfree, T8M_PSS, T8M_USS,
    T9M_GFX, T9M_MAIN, T9M_RES, T9M_CPU, T9M_MemAvailable, T9M_Memfree, T9M_PSS, T9M_USS) = (1 for _ in range(72))

    return (T1M_GFX, T1M_MAIN, T1M_RES, T1M_CPU, T1M_MemAvailable, T1M_Memfree, T1M_PSS, T1M_USS,
    T2M_GFX, T2M_MAIN, T2M_RES, T2M_CPU, T2M_MemAvailable, T2M_Memfree, T2M_PSS, T2M_USS,
    T3M_GFX, T3M_MAIN, T3M_RES, T3M_CPU, T3M_MemAvailable, T3M_Memfree, T3M_PSS, T3M_USS,
    T4M_GFX, T4M_MAIN, T4M_RES, T4M_CPU, T4M_MemAvailable, T4M_Memfree, T4M_PSS, T4M_USS,
    T5M_GFX, T5M_MAIN, T5M_RES, T5M_CPU, T5M_MemAvailable, T5M_Memfree, T5M_PSS, T5M_USS,
    T6M_GFX, T6M_MAIN, T6M_RES, T6M_CPU, T6M_MemAvailable, T6M_Memfree, T6M_PSS, T6M_USS,
    T7M_GFX, T7M_MAIN, T7M_RES, T7M_CPU, T7M_MemAvailable, T7M_Memfree, T7M_PSS, T7M_USS,
    T8M_GFX, T8M_MAIN, T8M_RES, T8M_CPU, T8M_MemAvailable, T8M_Memfree, T8M_PSS, T8M_USS,
    T9M_GFX, T9M_MAIN, T9M_RES, T9M_CPU, T9M_MemAvailable, T9M_Memfree, T9M_PSS, T9M_USS)

(T1M_GFX, T1M_MAIN, T1M_RES, T1M_CPU, T1M_MemAvailable, T1M_Memfree, T1M_PSS, T1M_USS,
T2M_GFX, T2M_MAIN, T2M_RES, T2M_CPU, T2M_MemAvailable, T2M_Memfree, T2M_PSS, T2M_USS,
T3M_GFX, T3M_MAIN, T3M_RES, T3M_CPU, T3M_MemAvailable, T3M_Memfree, T3M_PSS, T3M_USS,
T4M_GFX, T4M_MAIN, T4M_RES, T4M_CPU, T4M_MemAvailable, T4M_Memfree, T4M_PSS, T4M_USS,
T5M_GFX, T5M_MAIN, T5M_RES, T5M_CPU, T5M_MemAvailable, T5M_Memfree, T5M_PSS, T5M_USS,
T6M_GFX, T6M_MAIN, T6M_RES, T6M_CPU, T6M_MemAvailable, T6M_Memfree, T6M_PSS, T6M_USS,
T7M_GFX, T7M_MAIN, T7M_RES, T7M_CPU, T7M_MemAvailable, T7M_Memfree, T7M_PSS, T7M_USS,
T8M_GFX, T8M_MAIN, T8M_RES, T8M_CPU, T8M_MemAvailable, T8M_Memfree, T8M_PSS, T8M_USS,
T9M_GFX, T9M_MAIN, T9M_RES, T9M_CPU, T9M_MemAvailable, T9M_Memfree, T9M_PSS, T9M_USS) = var1()


print(T4M_GFX)
